//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.05 at 05:32:38 PM MSK 
//


package com.rest4j.impl.model;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FieldAccessType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="FieldAccessType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="readonly"/>
 *     &lt;enumeration value="writeonly"/>
 *     &lt;enumeration value="readwrite"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "FieldAccessType")
@XmlEnum
public enum FieldAccessType {

    @XmlEnumValue("readonly")
    READONLY("readonly"),
    @XmlEnumValue("writeonly")
    WRITEONLY("writeonly"),
    @XmlEnumValue("readwrite")
    READWRITE("readwrite");
    private final String value;

    FieldAccessType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static FieldAccessType fromValue(String v) {
        for (FieldAccessType c: FieldAccessType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
