//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.07.13 at 11:56:40 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://rest4j.com/api-description", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.rest4j.impl.model;
