//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.06 at 06:24:37 PM MSK 
//


package com.rest4j.impl.ext;

import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.rest4j.impl.ext package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ModelExt_QNAME = new QName("http://rest4j.com/api-description/ext", "model-ext");
    private final static QName _ParamExt_QNAME = new QName("http://rest4j.com/api-description/ext", "param-ext");
    private final static QName _EndpointExt_QNAME = new QName("http://rest4j.com/api-description/ext", "endpoint-ext");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.rest4j.impl.ext
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FieldExt }
     * 
     */
    public FieldExt createFieldExt() {
        return new FieldExt();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rest4j.com/api-description/ext", name = "model-ext")
    public JAXBElement<Object> createModelExt(Object value) {
        return new JAXBElement<Object>(_ModelExt_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rest4j.com/api-description/ext", name = "param-ext")
    public JAXBElement<Object> createParamExt(Object value) {
        return new JAXBElement<Object>(_ParamExt_QNAME, Object.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Object }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://rest4j.com/api-description/ext", name = "endpoint-ext")
    public JAXBElement<Object> createEndpointExt(Object value) {
        return new JAXBElement<Object>(_EndpointExt_QNAME, Object.class, null, value);
    }

}
