//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.06.06 at 06:24:37 PM MSK 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://rest4j.com/api-description/ext")
package com.rest4j.impl.ext;
